Repository Galiv/who-is-on-top, pull requests merged in 2021-03, with the labels that each got.

#17 Equipment
  equipment.txt
Labels: documentation

#18 Create jokes.txt
  jokes.txt
Labels: documentation

#23 Раунд 3
  Раунд 3. «ПОКАЖИ НАЗВУ».docx
Labels: boys, documentation, girls

#24 Final
  Раунд №7. «ФІНАЛ».docx
Labels: boys, documentation, girls

#26 Раунд №4. «ХТО Я?»
  Раунд №4. «ХТО Я_».docx
Labels: boys, girls
